plugins {
    id "com.android.application"
}

android {
    namespace "com.menteagil.offline"
    compileSdk 35

    defaultConfig {
        applicationId "com.menteagil.offline"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "1.2.0-mobile"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
