plugins {
    id "com.android.application"
}

android {
    namespace "com.menteagil.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.menteagil.app"
        minSdk 24
        targetSdk 35
        versionCode 111
        versionName "1.1.1"
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
